# Generated by Django 4.2.3 on 2024-02-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_department_alter_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='branch',
            field=models.CharField(choices=[('India', 'India'), ('England', 'England'), ('China', 'China')], default='India', max_length=30),
        ),
    ]
